version: '2'
services:
  php:
    image: webdevops/php-apache:ubuntu-16.04
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - APP_ENV=local
      - VIRTUAL_HOST=workshop.timitao
      - WEB_DOCUMENT_ROOT=/app/public
    ports:
      - 80:80
  composer:
    image: composer/composer
    working_dir: /app
    volumes_from:
      - php